[workspace]

members = [
    "Thunder",
    "Thunder/ShaderCompiler",
    "Thunder/DataDefinitionGenerated",
    "Thunder/Components",
    "Thunder/flecs-rs",
    "Thunder/flecs-rs-derive",
    "Thunder/gltf-loader",
]