[workspace]
members = [
    "Thunder",
    "Thunder/ShaderCompiler",
    "Thunder/DataDefinitionGenerated",
    "Thunder/Components",
    "Thunder/flecs-rs",
    "Thunder/flecs-rs-derive",
    "Thunder/gltf-loader",
    "Thunder/flatbuffer-derive",
]

[patch.crates-io]
gltf = {path = "ThirdParty/gltf" }