// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ANIMATIONDATABASE_TEMPEST_DEFINITION_H_
#define FLATBUFFERS_GENERATED_ANIMATIONDATABASE_TEMPEST_DEFINITION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "CommonTypes_generated.h"

namespace Tempest {
namespace Definition {

struct Bone;

struct Skeleton;

struct Animation;

struct AnimationDatabase;
struct AnimationDatabaseBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Bone FLATBUFFERS_FINAL_CLASS {
 private:
  Common::Tempest::Quat local_rotation_;
  Common::Tempest::Vec3 local_position_;
  uint32_t parent_;

 public:
  Bone()
      : local_rotation_(),
        local_position_(),
        parent_(0) {
  }
  Bone(const Common::Tempest::Quat &_local_rotation, const Common::Tempest::Vec3 &_local_position, uint32_t _parent)
      : local_rotation_(_local_rotation),
        local_position_(_local_position),
        parent_(::flatbuffers::EndianScalar(_parent)) {
  }
  const Common::Tempest::Quat &local_rotation() const {
    return local_rotation_;
  }
  const Common::Tempest::Vec3 &local_position() const {
    return local_position_;
  }
  uint32_t parent() const {
    return ::flatbuffers::EndianScalar(parent_);
  }
};
FLATBUFFERS_STRUCT_END(Bone, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Skeleton FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t start_index_;
  uint32_t count_;
  uint32_t inverse_bind_matrices_start_index_;

 public:
  Skeleton()
      : start_index_(0),
        count_(0),
        inverse_bind_matrices_start_index_(0) {
  }
  Skeleton(uint32_t _start_index, uint32_t _count, uint32_t _inverse_bind_matrices_start_index)
      : start_index_(::flatbuffers::EndianScalar(_start_index)),
        count_(::flatbuffers::EndianScalar(_count)),
        inverse_bind_matrices_start_index_(::flatbuffers::EndianScalar(_inverse_bind_matrices_start_index)) {
  }
  uint32_t start_index() const {
    return ::flatbuffers::EndianScalar(start_index_);
  }
  uint32_t count() const {
    return ::flatbuffers::EndianScalar(count_);
  }
  uint32_t inverse_bind_matrices_start_index() const {
    return ::flatbuffers::EndianScalar(inverse_bind_matrices_start_index_);
  }
};
FLATBUFFERS_STRUCT_END(Skeleton, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Animation FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t skeleton_index_;
  uint32_t num_frames_;
  uint32_t start_index_;
  uint32_t count_;

 public:
  Animation()
      : skeleton_index_(0),
        num_frames_(0),
        start_index_(0),
        count_(0) {
  }
  Animation(uint32_t _skeleton_index, uint32_t _num_frames, uint32_t _start_index, uint32_t _count)
      : skeleton_index_(::flatbuffers::EndianScalar(_skeleton_index)),
        num_frames_(::flatbuffers::EndianScalar(_num_frames)),
        start_index_(::flatbuffers::EndianScalar(_start_index)),
        count_(::flatbuffers::EndianScalar(_count)) {
  }
  uint32_t skeleton_index() const {
    return ::flatbuffers::EndianScalar(skeleton_index_);
  }
  uint32_t num_frames() const {
    return ::flatbuffers::EndianScalar(num_frames_);
  }
  uint32_t start_index() const {
    return ::flatbuffers::EndianScalar(start_index_);
  }
  uint32_t count() const {
    return ::flatbuffers::EndianScalar(count_);
  }
};
FLATBUFFERS_STRUCT_END(Animation, 16);

struct AnimationDatabase FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationDatabaseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SKELETONS = 4,
    VT_BONES = 6,
    VT_ANIMATIONS = 8,
    VT_ANIM_DATA = 10,
    VT_INVERSE_BIND_MATRICES = 12
  };
  const ::flatbuffers::Vector<const Tempest::Definition::Skeleton *> *skeletons() const {
    return GetPointer<const ::flatbuffers::Vector<const Tempest::Definition::Skeleton *> *>(VT_SKELETONS);
  }
  const ::flatbuffers::Vector<const Tempest::Definition::Bone *> *bones() const {
    return GetPointer<const ::flatbuffers::Vector<const Tempest::Definition::Bone *> *>(VT_BONES);
  }
  const ::flatbuffers::Vector<const Tempest::Definition::Animation *> *animations() const {
    return GetPointer<const ::flatbuffers::Vector<const Tempest::Definition::Animation *> *>(VT_ANIMATIONS);
  }
  const ::flatbuffers::Vector<uint8_t> *anim_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_ANIM_DATA);
  }
  const ::flatbuffers::Vector<uint8_t> *inverse_bind_matrices() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_INVERSE_BIND_MATRICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SKELETONS) &&
           verifier.VerifyVector(skeletons()) &&
           VerifyOffset(verifier, VT_BONES) &&
           verifier.VerifyVector(bones()) &&
           VerifyOffset(verifier, VT_ANIMATIONS) &&
           verifier.VerifyVector(animations()) &&
           VerifyOffset(verifier, VT_ANIM_DATA) &&
           verifier.VerifyVector(anim_data()) &&
           VerifyOffset(verifier, VT_INVERSE_BIND_MATRICES) &&
           verifier.VerifyVector(inverse_bind_matrices()) &&
           verifier.EndTable();
  }
};

struct AnimationDatabaseBuilder {
  typedef AnimationDatabase Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_skeletons(::flatbuffers::Offset<::flatbuffers::Vector<const Tempest::Definition::Skeleton *>> skeletons) {
    fbb_.AddOffset(AnimationDatabase::VT_SKELETONS, skeletons);
  }
  void add_bones(::flatbuffers::Offset<::flatbuffers::Vector<const Tempest::Definition::Bone *>> bones) {
    fbb_.AddOffset(AnimationDatabase::VT_BONES, bones);
  }
  void add_animations(::flatbuffers::Offset<::flatbuffers::Vector<const Tempest::Definition::Animation *>> animations) {
    fbb_.AddOffset(AnimationDatabase::VT_ANIMATIONS, animations);
  }
  void add_anim_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> anim_data) {
    fbb_.AddOffset(AnimationDatabase::VT_ANIM_DATA, anim_data);
  }
  void add_inverse_bind_matrices(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> inverse_bind_matrices) {
    fbb_.AddOffset(AnimationDatabase::VT_INVERSE_BIND_MATRICES, inverse_bind_matrices);
  }
  explicit AnimationDatabaseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimationDatabase> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimationDatabase>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimationDatabase> CreateAnimationDatabase(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Tempest::Definition::Skeleton *>> skeletons = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Tempest::Definition::Bone *>> bones = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Tempest::Definition::Animation *>> animations = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> anim_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> inverse_bind_matrices = 0) {
  AnimationDatabaseBuilder builder_(_fbb);
  builder_.add_inverse_bind_matrices(inverse_bind_matrices);
  builder_.add_anim_data(anim_data);
  builder_.add_animations(animations);
  builder_.add_bones(bones);
  builder_.add_skeletons(skeletons);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimationDatabase> CreateAnimationDatabaseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Tempest::Definition::Skeleton> *skeletons = nullptr,
    const std::vector<Tempest::Definition::Bone> *bones = nullptr,
    const std::vector<Tempest::Definition::Animation> *animations = nullptr,
    const std::vector<uint8_t> *anim_data = nullptr,
    const std::vector<uint8_t> *inverse_bind_matrices = nullptr) {
  auto skeletons__ = skeletons ? _fbb.CreateVectorOfStructs<Tempest::Definition::Skeleton>(*skeletons) : 0;
  auto bones__ = bones ? _fbb.CreateVectorOfStructs<Tempest::Definition::Bone>(*bones) : 0;
  auto animations__ = animations ? _fbb.CreateVectorOfStructs<Tempest::Definition::Animation>(*animations) : 0;
  auto anim_data__ = anim_data ? _fbb.CreateVector<uint8_t>(*anim_data) : 0;
  auto inverse_bind_matrices__ = inverse_bind_matrices ? _fbb.CreateVector<uint8_t>(*inverse_bind_matrices) : 0;
  return Tempest::Definition::CreateAnimationDatabase(
      _fbb,
      skeletons__,
      bones__,
      animations__,
      anim_data__,
      inverse_bind_matrices__);
}

inline const Tempest::Definition::AnimationDatabase *GetAnimationDatabase(const void *buf) {
  return ::flatbuffers::GetRoot<Tempest::Definition::AnimationDatabase>(buf);
}

inline const Tempest::Definition::AnimationDatabase *GetSizePrefixedAnimationDatabase(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Tempest::Definition::AnimationDatabase>(buf);
}

inline const char *AnimationDatabaseIdentifier() {
  return "TADB";
}

inline bool AnimationDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, AnimationDatabaseIdentifier());
}

inline bool SizePrefixedAnimationDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, AnimationDatabaseIdentifier(), true);
}

inline bool VerifyAnimationDatabaseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Tempest::Definition::AnimationDatabase>(AnimationDatabaseIdentifier());
}

inline bool VerifySizePrefixedAnimationDatabaseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Tempest::Definition::AnimationDatabase>(AnimationDatabaseIdentifier());
}

inline const char *AnimationDatabaseExtension() {
  return "tab";
}

inline void FinishAnimationDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tempest::Definition::AnimationDatabase> root) {
  fbb.Finish(root, AnimationDatabaseIdentifier());
}

inline void FinishSizePrefixedAnimationDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tempest::Definition::AnimationDatabase> root) {
  fbb.FinishSizePrefixed(root, AnimationDatabaseIdentifier());
}

}  // namespace Definition
}  // namespace Tempest

#endif  // FLATBUFFERS_GENERATED_ANIMATIONDATABASE_TEMPEST_DEFINITION_H_
