// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMONTYPES_COMMON_TEMPEST_H_
#define FLATBUFFERS_GENERATED_COMMONTYPES_COMMON_TEMPEST_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace Common {
namespace Tempest {

struct Vec3;

struct Quat;

struct Color;

enum PhysicsShapeFilter : uint32_t {
  PhysicsShapeFilter_NonDrivableSurface = 65535,
  PhysicsShapeFilter_DrivableSurface = 4294901760,
  PhysicsShapeFilter_MIN = PhysicsShapeFilter_NonDrivableSurface,
  PhysicsShapeFilter_MAX = PhysicsShapeFilter_DrivableSurface
};

inline const PhysicsShapeFilter (&EnumValuesPhysicsShapeFilter())[2] {
  static const PhysicsShapeFilter values[] = {
    PhysicsShapeFilter_NonDrivableSurface,
    PhysicsShapeFilter_DrivableSurface
  };
  return values;
}

inline const char *EnumNamePhysicsShapeFilter(PhysicsShapeFilter e) {
  switch (e) {
    case PhysicsShapeFilter_NonDrivableSurface: return "NonDrivableSurface";
    case PhysicsShapeFilter_DrivableSurface: return "DrivableSurface";
    default: return "";
  }
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Quat FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Quat()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Quat(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Quat, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Color FLATBUFFERS_FINAL_CLASS {
 private:
  float r_;
  float g_;
  float b_;
  float a_;

 public:
  Color()
      : r_(0),
        g_(0),
        b_(0),
        a_(0) {
  }
  Color(float _r, float _g, float _b, float _a)
      : r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)),
        a_(::flatbuffers::EndianScalar(_a)) {
  }
  float r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  float g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  float b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
  float a() const {
    return ::flatbuffers::EndianScalar(a_);
  }
};
FLATBUFFERS_STRUCT_END(Color, 16);

}  // namespace Tempest
}  // namespace Common

#endif  // FLATBUFFERS_GENERATED_COMMONTYPES_COMMON_TEMPEST_H_
