// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PHYSICSDATABASE_TEMPEST_DEFINITION_H_
#define FLATBUFFERS_GENERATED_PHYSICSDATABASE_TEMPEST_DEFINITION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace Tempest {
namespace Definition {

struct PhysicsDatabase;
struct PhysicsDatabaseBuilder;

struct PhysicsDatabase FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicsDatabaseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INITIAL_PHYSICS_SCENE = 4,
    VT_PREFABS_SCENE = 6
  };
  const ::flatbuffers::Vector<uint8_t> *initial_physics_scene() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_INITIAL_PHYSICS_SCENE);
  }
  const ::flatbuffers::Vector<uint8_t> *prefabs_scene() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PREFABS_SCENE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INITIAL_PHYSICS_SCENE) &&
           verifier.VerifyVector(initial_physics_scene()) &&
           VerifyOffset(verifier, VT_PREFABS_SCENE) &&
           verifier.VerifyVector(prefabs_scene()) &&
           verifier.EndTable();
  }
};

struct PhysicsDatabaseBuilder {
  typedef PhysicsDatabase Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_initial_physics_scene(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> initial_physics_scene) {
    fbb_.AddOffset(PhysicsDatabase::VT_INITIAL_PHYSICS_SCENE, initial_physics_scene);
  }
  void add_prefabs_scene(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> prefabs_scene) {
    fbb_.AddOffset(PhysicsDatabase::VT_PREFABS_SCENE, prefabs_scene);
  }
  explicit PhysicsDatabaseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicsDatabase> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicsDatabase>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicsDatabase> CreatePhysicsDatabase(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> initial_physics_scene = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> prefabs_scene = 0) {
  PhysicsDatabaseBuilder builder_(_fbb);
  builder_.add_prefabs_scene(prefabs_scene);
  builder_.add_initial_physics_scene(initial_physics_scene);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PhysicsDatabase> CreatePhysicsDatabaseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *initial_physics_scene = nullptr,
    const std::vector<uint8_t> *prefabs_scene = nullptr) {
  auto initial_physics_scene__ = initial_physics_scene ? _fbb.CreateVector<uint8_t>(*initial_physics_scene) : 0;
  auto prefabs_scene__ = prefabs_scene ? _fbb.CreateVector<uint8_t>(*prefabs_scene) : 0;
  return Tempest::Definition::CreatePhysicsDatabase(
      _fbb,
      initial_physics_scene__,
      prefabs_scene__);
}

inline const Tempest::Definition::PhysicsDatabase *GetPhysicsDatabase(const void *buf) {
  return ::flatbuffers::GetRoot<Tempest::Definition::PhysicsDatabase>(buf);
}

inline const Tempest::Definition::PhysicsDatabase *GetSizePrefixedPhysicsDatabase(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Tempest::Definition::PhysicsDatabase>(buf);
}

inline const char *PhysicsDatabaseIdentifier() {
  return "TPDB";
}

inline bool PhysicsDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PhysicsDatabaseIdentifier());
}

inline bool SizePrefixedPhysicsDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PhysicsDatabaseIdentifier(), true);
}

inline bool VerifyPhysicsDatabaseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Tempest::Definition::PhysicsDatabase>(PhysicsDatabaseIdentifier());
}

inline bool VerifySizePrefixedPhysicsDatabaseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Tempest::Definition::PhysicsDatabase>(PhysicsDatabaseIdentifier());
}

inline const char *PhysicsDatabaseExtension() {
  return "tpb";
}

inline void FinishPhysicsDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tempest::Definition::PhysicsDatabase> root) {
  fbb.Finish(root, PhysicsDatabaseIdentifier());
}

inline void FinishSizePrefixedPhysicsDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tempest::Definition::PhysicsDatabase> root) {
  fbb.FinishSizePrefixed(root, PhysicsDatabaseIdentifier());
}

}  // namespace Definition
}  // namespace Tempest

#endif  // FLATBUFFERS_GENERATED_PHYSICSDATABASE_TEMPEST_DEFINITION_H_
