// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SOUNDDATABASE_TEMPEST_DEFINITION_H_
#define FLATBUFFERS_GENERATED_SOUNDDATABASE_TEMPEST_DEFINITION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace Tempest {
namespace Definition {

struct SoundDatabase;
struct SoundDatabaseBuilder;

struct SoundDatabase FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SoundDatabaseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BACKGROUND_MUSIC = 4
  };
  const ::flatbuffers::Vector<uint8_t> *background_music() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BACKGROUND_MUSIC);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BACKGROUND_MUSIC) &&
           verifier.VerifyVector(background_music()) &&
           verifier.EndTable();
  }
};

struct SoundDatabaseBuilder {
  typedef SoundDatabase Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_background_music(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> background_music) {
    fbb_.AddOffset(SoundDatabase::VT_BACKGROUND_MUSIC, background_music);
  }
  explicit SoundDatabaseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SoundDatabase> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SoundDatabase>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SoundDatabase> CreateSoundDatabase(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> background_music = 0) {
  SoundDatabaseBuilder builder_(_fbb);
  builder_.add_background_music(background_music);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SoundDatabase> CreateSoundDatabaseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *background_music = nullptr) {
  auto background_music__ = background_music ? _fbb.CreateVector<uint8_t>(*background_music) : 0;
  return Tempest::Definition::CreateSoundDatabase(
      _fbb,
      background_music__);
}

inline const Tempest::Definition::SoundDatabase *GetSoundDatabase(const void *buf) {
  return ::flatbuffers::GetRoot<Tempest::Definition::SoundDatabase>(buf);
}

inline const Tempest::Definition::SoundDatabase *GetSizePrefixedSoundDatabase(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Tempest::Definition::SoundDatabase>(buf);
}

inline const char *SoundDatabaseIdentifier() {
  return "TSDB";
}

inline bool SoundDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SoundDatabaseIdentifier());
}

inline bool SizePrefixedSoundDatabaseBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SoundDatabaseIdentifier(), true);
}

inline bool VerifySoundDatabaseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Tempest::Definition::SoundDatabase>(SoundDatabaseIdentifier());
}

inline bool VerifySizePrefixedSoundDatabaseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Tempest::Definition::SoundDatabase>(SoundDatabaseIdentifier());
}

inline const char *SoundDatabaseExtension() {
  return "tsb";
}

inline void FinishSoundDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tempest::Definition::SoundDatabase> root) {
  fbb.Finish(root, SoundDatabaseIdentifier());
}

inline void FinishSizePrefixedSoundDatabaseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tempest::Definition::SoundDatabase> root) {
  fbb.FinishSizePrefixed(root, SoundDatabaseIdentifier());
}

}  // namespace Definition
}  // namespace Tempest

#endif  // FLATBUFFERS_GENERATED_SOUNDDATABASE_TEMPEST_DEFINITION_H_
