// automatically generated by the FlatBuffers compiler, do not modify

use std::cmp::Ordering;
use std::mem;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(unused_imports, dead_code)]
pub mod tempest {

    use std::cmp::Ordering;
    use std::mem;

    extern crate flatbuffers;
    use self::flatbuffers::EndianScalar;
    #[allow(unused_imports, dead_code)]
    pub mod definition {

        use std::cmp::Ordering;
        use std::mem;

        extern crate flatbuffers;
        use self::flatbuffers::EndianScalar;

        pub enum LevelOffset {}
        #[derive(Copy, Clone, Debug, PartialEq)]

        pub struct Level<'a> {
            pub _tab: flatbuffers::Table<'a>,
        }

        impl<'a> flatbuffers::Follow<'a> for Level<'a> {
            type Inner = Level<'a>;
            #[inline]
            fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: flatbuffers::Table { buf: buf, loc: loc },
                }
            }
        }

        impl<'a> Level<'a> {
            #[inline]
            pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
                Level { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
                _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
                args: &'args LevelArgs<'args>,
            ) -> flatbuffers::WIPOffset<Level<'bldr>> {
                let mut builder = LevelBuilder::new(_fbb);
                if let Some(x) = args.entities {
                    builder.add_entities(x);
                }
                if let Some(x) = args.name {
                    builder.add_name(x);
                }
                builder.finish()
            }

            pub const VT_NAME: flatbuffers::VOffsetT = 4;
            pub const VT_ENTITIES: flatbuffers::VOffsetT = 6;

            #[inline]
            pub fn name(&self) -> Option<&'a str> {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(Level::VT_NAME, None)
            }
            #[inline]
            pub fn entities(&self) -> Option<&'a [u8]> {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        Level::VT_ENTITIES,
                        None,
                    )
                    .map(|v| v.safe_slice())
            }
        }

        pub struct LevelArgs<'a> {
            pub name: Option<flatbuffers::WIPOffset<&'a str>>,
            pub entities: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
        }
        impl<'a> Default for LevelArgs<'a> {
            #[inline]
            fn default() -> Self {
                LevelArgs {
                    name: None,
                    entities: None,
                }
            }
        }
        pub struct LevelBuilder<'a: 'b, 'b> {
            fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
            start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b> LevelBuilder<'a, 'b> {
            #[inline]
            pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b str>) {
                self.fbb_
                    .push_slot_always::<flatbuffers::WIPOffset<_>>(Level::VT_NAME, name);
            }
            #[inline]
            pub fn add_entities(
                &mut self,
                entities: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_
                    .push_slot_always::<flatbuffers::WIPOffset<_>>(Level::VT_ENTITIES, entities);
            }
            #[inline]
            pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> LevelBuilder<'a, 'b> {
                let start = _fbb.start_table();
                LevelBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> flatbuffers::WIPOffset<Level<'a>> {
                let o = self.fbb_.end_table(self.start_);
                flatbuffers::WIPOffset::new(o.value())
            }
        }

        #[inline]
        pub fn get_root_as_level<'a>(buf: &'a [u8]) -> Level<'a> {
            flatbuffers::get_root::<Level<'a>>(buf)
        }

        #[inline]
        pub fn get_size_prefixed_root_as_level<'a>(buf: &'a [u8]) -> Level<'a> {
            flatbuffers::get_size_prefixed_root::<Level<'a>>(buf)
        }

        pub const LEVEL_IDENTIFIER: &'static str = "TLDB";

        #[inline]
        pub fn level_buffer_has_identifier(buf: &[u8]) -> bool {
            return flatbuffers::buffer_has_identifier(buf, LEVEL_IDENTIFIER, false);
        }

        #[inline]
        pub fn level_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
            return flatbuffers::buffer_has_identifier(buf, LEVEL_IDENTIFIER, true);
        }

        pub const LEVEL_EXTENSION: &'static str = "tlb";

        #[inline]
        pub fn finish_level_buffer<'a, 'b>(
            fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
            root: flatbuffers::WIPOffset<Level<'a>>,
        ) {
            fbb.finish(root, Some(LEVEL_IDENTIFIER));
        }

        #[inline]
        pub fn finish_size_prefixed_level_buffer<'a, 'b>(
            fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
            root: flatbuffers::WIPOffset<Level<'a>>,
        ) {
            fbb.finish_size_prefixed(root, Some(LEVEL_IDENTIFIER));
        }
    } // pub mod Definition
} // pub mod Tempest
